language: node_js
node_js:
  - "12"
services:
  - docker

install: true

script:
  - npm run build
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker build -t pugbabu/docker_test:latest .
  - docker push pugbabu/docker_test:latest

